# Workflow name
name: 'Chromatic Deployment'

# Event for the workflow
on:
  push:
    branches: [main, change-task-background]
  pull_request:
    branches: [main, change-task-background]
    workflow_dispatch:

# List of jobs
jobs:
  test:
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - uses: actions/checkout@v1
      - run: yarn
        #👇 Adds Chromatic as a step in the workflow
      - uses: chromaui/action@v1
        # Options required for Chromatic's GitHub Action
        with:
          #👇 Chromatic projectToken, see https://storybook.js.org/tutorials/intro-to-storybook/react/fr/deploy/ to obtain it
          projectToken: ${{ da56d7e91a34 }}
          token: ${{ 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 }}
